### ISSUE TITLE
Scenestorage error

### ISSUE THREAD

**Issue by Ged2323** [LostMoa/wwdc20#2]
Hi, 
I was trying out your code and I'm getting this error.  What am I missing? 
Thanks in advance.

Here is the error.
SceneStorageDemo[6532:188464] Fatal error: @SceneStorage is only for use with SwiftUI App Lifecycle.: file SwiftUI, line 0

**Comment by nataliapanferova** [comment]
I get this error if I try to use SceneStorage in an App with UIKit App Delegate life cycle.

When you create a project in Xcode you can choose what life cycle to use: 
![image](https://user-images.githubusercontent.com/15342922/86500578-440c3580-bde6-11ea-9f87-29119a332e38.png)

Looks like for SceneStorage to work it needs to be SwiftUI App.

**Comment by Ged2323** [comment]
Thanks Natalia that solved it.
